### PR TITLE
Sahara on Mitaka

### PR DESCRIPTION
**Pull request by jeremyfreudberg**
Here it is. It works in staging area fine. Seems good enough for production.

Two new Hiera variables:
`quickstack::params::sahara_production` (true/false) and `quickstack::params::ha_controller_ip_public` (self-explanatory)  

If the first one is falsey then the second one can be `null`

### CODE REVIEW

**Comment by radonm** [comment]
Actually correction : quickstack::params::ha_controller_ip_public is a duplicate to ha::vip: can't you re-use ha::vip ?

**Comment by jeremyfreudberg** [comment]
Oops... yes it's the same. I will fix it soon. This means I can get rid of `sahara_production` too, since I was only using it to make `ha_controller_ip_public` optional

**Comment by radonm** [comment]
And another thought - what is that ip used for? Normally should be DNS name ?

**Comment by jeremyfreudberg** [comment]
This is for Hadoop performance boost. DNS in user VM is slow so I modify Sahara codebase to inject /etc/hosts entry for Keystone.

**Comment by radonm** [comment]
Hmm then we need to fix the DNS issue, also if you do ssl with ip address that means disabling cert validation checks.

**Comment by jeremyfreudberg** [comment]
If we could speed up DNS that would be great.  

There's no issue with cert validation: the Hadoop job still uses keystone endpoint hostname for swift auth. We're just skipping the resolution of the name over DNS and using hosts file instead

**Comment by radonm** [comment]
Ooops right /etc/hosts, but still hosts file management always creates issues at some point later.... 2 things - try using 128.31.28.11 as first DNS server, and others have found that issue and Laura had a different solution modifying resolver library settings.

**Comment by kamfonik** [comment]
It should speed up DNS if you add this line to /etc/resolv.conf:
`options single-request`
Some slowness happens because it is waiting for an ipv6 request to time out, this bypasses that.

**Comment by jeremyfreudberg** [comment]
The `resolv.conf` trick is what I want - and I can build this directly into the Sahara image instead so we don't have to do it in this roundabout way with Puppet.  

I'll have some time later to finish up these changes

**Comment by jeremyfreudberg** [comment]
Decided to keep the `/etc/hosts` generation code here. I'd rather not have to generate a ton of new Sahara images. Better to just change the code once here.  

Also a minor UX fix for Spark in Sahara

**Comment by kamfonik** [comment]
+1

**Comment by radonm** [comment]
+2

**Pull request merged**
